name: Run Gradle on PRs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Atlas
        uses: ariga/setup-atlas@master

      - name: Build and test Plugin
        run: ./gradlew build

      - name: Build and test Sample Project
        run: |
          cd examples/hibernate_standalone/
          ./gradlew build

      - name: Test default schema task - includeBuild
        run: |
          cd examples/hibernate_standalone/
          ./gradlew -q schema > schema_output
          diff schema_output src/test/expected_default_schema

      - name: Integration tests with local plugin repo
        run: |
          ./gradlew publishAllPublicationsToLocalPluginRepositoryRepository
          cd examples/with_local_plugin_repository
          ./gradlew -q schema | tee schema_output
          diff schema_output src/test/expected_default_schema
          ./gradlew integrationTests

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: E2E test spring project
        run: |
          cd examples/with_spring_gradle
          output=$(atlas migrate diff --env hibernate)
          [ "$output" = "The migration directory is synced with the desired state, no changes to be made" ] || echo "unexpected output: $output"