name: Run Gradle on PRs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Maven Plugin
        run: |
          mvn clean install

      - name: Integration tests with maven plugin
        run: |
          cd examples/maven_project_example
          mvn compile io.atlasgo:hibernate-provider-maven-plugin:0.1:schema -Dexec.classpathScope=runtime -q

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Setup Atlas
        uses: ariga/setup-atlas@master

      - name: Build and test Plugin
        run: ./gradlew build

      - name: Build and test Sample Project
        run: |
          cd examples/hibernate_standalone/
          ./gradlew build

      - name: Test default schema task - includeBuild
        run: |
          cd examples/hibernate_standalone/
          ./gradlew -q schema > schema_output
          diff schema_output src/test/expected_default_schema

      - name: Integration tests with local plugin repo
        run: |
          ./gradlew publishAllPublicationsToLocalPluginRepositoryRepository
          cd examples/with_local_plugin_repository
          ./gradlew -q schema | tee schema_output
          diff schema_output src/test/expected_default_schema
          ./gradlew integrationTests

      - name: Integration tests with unsupported schema
        run: |
          cd examples/with_forbidden_generation_type
          if (set -o pipefail && atlas schema inspect --env hibernate --url env://src 2>&1 | tee /tmp/forbidden_output); then
              echo "expected schema extraction to fail due to an unsupported SQL command" && false
          else
              echo "command failed successfully, checking output contains error string"
              grep -i "unsupported.sql.command" /tmp/forbidden_output || (echo "Failed output comparison, output was:" && cat /tmp/forbidden_output && false)
              echo "error string found"
          fi

      - name: Build Maven Plugin
        run: |
          mvn clean install

      - name: Integration tests with maven plugin
        run: |
          cd examples/maven_project_example
          mvn compile io.atlasgo:hibernate-provider-maven-plugin:0.1:schema -Dexec.classpathScope=runtime -q

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: E2E test spring project
        run: |
          cd examples/with_spring_gradle
          output=$(atlas migrate diff --env hibernate)
          [ "$output" = "The migration directory is synced with the desired state, no changes to be made" ] || (echo "diff detected? unexpected output: $output"; ls -l migrations; exit 1)