name: Run Gradle on PRs
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Plugin
        run: ./gradlew build

      - name: Build Sample Project
        run: |
          cd examples/hibernate_standalone/
          ./gradlew build

      - name: Test default schema task
        run: |
          set -x
          cd examples/hibernate_standalone/
          ./gradlew -q schema > schema_output
          diff schema_output src/test/expected_default_schema